
linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocognit

  presets:
    - bugs
    - sql
run:
  timeout: "5m"
  tests: true
