# This Dockerfile embeds a pre-built binary for the given Linux architecture
# Binaries are supplied by GoReleaser.

FROM alpine:3.24.1

# TARGETARCH can be "amd64" or "arm64"
ARG TARGETARCH
ARG TARGETVARIANT

WORKDIR /app

RUN apk add --no-cache curl su-exec

COPY linux/${TARGETARCH}/${TARGETVARIANT}/pocket-id /app/pocket-id
COPY ./scripts/docker /app/docker

EXPOSE 1411
ENV APP_ENV=production

HEALTHCHECK --interval=90s --timeout=5s --start-period=10s --retries=3 CMD [ "/app/pocket-id", "healthcheck" ]

ENTRYPOINT ["/app/docker/entrypoint.sh"]
CMD ["/app/pocket-id"]
