ALTER TABLE audit_logs ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE audit_logs ALTER COLUMN user_agent DROP NOT NULL;
ALTER TABLE kv ALTER COLUMN value DROP NOT NULL;
ALTER TABLE oidc_clients ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE users ALTER COLUMN first_name DROP NOT NULL;
ALTER TABLE users ALTER COLUMN last_name DROP NOT NULL;
ALTER TABLE webauthn_credentials ALTER COLUMN created_at DROP NOT NULL;
